name: general

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: download dependencies
        run: |
          go version
          go mod download
      - name: build
        run: |
          go build ./cmd/server/